# Generated by Django 5.0.7 on 2024-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('sender_name', models.CharField(max_length=128, verbose_name='Sender Name')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Sender Email')),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Us Message',
                'verbose_name_plural': 'Contact Us Messages',
            },
        ),
    ]
